In [1]:
# standard library imports
import sys
sys.path.append("../")

# third party imports
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# local imports
from src.data_generator import DataGenerator
from src.models import MADModel, MarkowitzModel

# Downloading and Loading the Data

In [ ]:
# Create dataset
data_generator = DataGenerator()
# data_generator()

No need to create the dataset again as it has already been generated and made available in the repository.

In [2]:
df = pd.read_csv("../data/nasdaq_adj_closing_prices.csv", index_col="Date")
df.index = pd.to_datetime(df.index)

In [9]:
past_5_years = df.loc["2018-01-01":"2023-11-01"]
past_5_years = past_5_years.dropna(axis=1)
past_5_years = past_5_years.sample(30, axis=1)

In [10]:
mad_model = MADModel(past_5_years, 0.05, "2021-01-01")
w = mad_model()

w

array([-4.10458675e-13, -3.18546007e-13,  6.82948751e-13, -3.43787445e-13,
        2.84495564e-13, -3.06900287e-13,  6.89109575e-01, -3.50931132e-13,
        1.74343083e-01,  1.90449585e-11, -2.60237122e-13, -2.71448749e-13,
       -2.40491142e-13,  2.01913156e-11,  2.05463289e-12, -3.22651966e-13,
       -1.86621801e-13,  4.78272723e-13,  1.26992982e-12, -5.65673389e-14,
       -3.32305852e-13, -5.20630917e-13, -2.33021904e-13, -1.32585951e-13,
        1.67046402e-13,  2.90520448e-13, -2.09597483e-13, -1.29249295e-13,
        1.76979506e-13,  1.36547343e-01])

In [11]:
mw_model = MarkowitzModel(past_5_years, 0.05, "2021-01-01")
w = mw_model()

w

Minimum eigenvalue: 0.022087659363357735


array([-1.11010871e-23, -2.14569735e-23, -1.78532470e-23, -1.14474292e-24,
       -2.06269011e-23,  4.96422664e-24,  7.05459024e-01, -5.61120928e-24,
        1.64761847e-01, -5.63174396e-24, -9.30940091e-25,  2.40891210e-24,
       -3.06713559e-24,  1.44736126e-23,  1.22034456e-23, -2.78843665e-24,
       -2.42465077e-23,  3.28163888e-24, -1.05380125e-23,  7.47444134e-24,
        2.51976482e-23, -9.64176750e-24, -2.79004175e-24, -1.80015161e-24,
        1.02568685e-23, -1.24039212e-24, -3.53492430e-24, -6.76738007e-25,
        8.82431093e-24,  1.29779129e-01])

In [12]:
mw_model = MarkowitzModel(past_5_years, 0.05, "2021-01-01", use_covariance=False)
w = mw_model()

w

array([-2.99646174e-12, -2.54674160e-12, -3.15197839e-12, -2.19115520e-12,
       -4.13072481e-12, -4.70205484e-13,  7.05459124e-01, -1.57004121e-12,
        1.64761824e-01, -1.31280666e-12, -8.78933867e-13,  9.26618695e-13,
       -1.72497394e-12,  7.56787369e-13,  1.28614956e-12, -2.90474101e-12,
       -4.26841018e-12, -8.57359758e-14, -4.37384349e-13, -1.26433740e-13,
        9.48445625e-13, -4.69037015e-12, -1.25934647e-12,  1.86632958e-13,
        7.98629998e-14, -1.80488775e-12, -8.49446278e-13, -1.26332036e-12,
        1.28171196e-12,  1.29779052e-01])